[[drone]]
id = 1
connected_node_ids = [2, 3, 16]
pdr = 0.2

[[drone]]
id = 2
connected_node_ids = [1, 4, 5, 18]
pdr = 0.3

[[drone]]
id = 3
connected_node_ids = [1, 6, 7, 19]
pdr = 0.25

[[drone]]
id = 4
connected_node_ids = [2, 8, 9]
pdr = 0.22

[[drone]]
id = 5
connected_node_ids = [2, 10, 11, 19]
pdr = 0.18

[[drone]]
id = 6
connected_node_ids = [3, 12, 13]
pdr = 0.27

[[drone]]
id = 7
connected_node_ids = [3, 14, 15]
pdr = 0.24

[[drone]]
id = 8
connected_node_ids = [4, 17]
pdr = 0.2

[[drone]]
id = 9
connected_node_ids = [4, 17]
pdr = 0.2

[[drone]]
id = 10
connected_node_ids = [5, 17]
pdr = 0.2

[[drone]]
id = 11
connected_node_ids = [5, 17]
pdr = 0.2

[[drone]]
id = 12
connected_node_ids = [6, 17]
pdr = 0.2

[[drone]]
id = 13
connected_node_ids = [6, 17]
pdr = 0.2

[[drone]]
id = 14
connected_node_ids = [7, 17]
pdr = 0.2

[[drone]]
id = 15
connected_node_ids = [7, 17]
pdr = 0.2

[[client]]
id = 16
connected_drone_ids = [1]

[[client]]
id = 18
connected_drone_ids = [2]

[[server]]
id = 17
connected_drone_ids = [8, 9, 10, 11, 12, 13, 14, 15]

[[server]]
id = 19
connected_drone_ids = [3, 5]