[[drone]]
id = 1
connected_node_ids = [2, 3]
pdr = 0.05

[[drone]]
id = 2
connected_node_ids = [1, 4, 5]
pdr = 0.05

[[drone]]
id = 3
connected_node_ids = [1, 6, 7]
pdr = 0.05

[[drone]]
id = 4
connected_node_ids = [2, 8, 11, 15]
pdr = 0.05

[[drone]]
id = 5
connected_node_ids = [2, 8, 12, 15]
pdr = 0.05

[[drone]]
id = 6
connected_node_ids = [3, 9, 13]
pdr = 0.05

[[drone]]
id = 7
connected_node_ids = [3, 9, 14]
pdr = 0.05

[[drone]]
id = 8
connected_node_ids = [4, 5, 10]
pdr = 0.05

[[drone]]
id = 9
connected_node_ids = [6, 7, 10]
pdr = 0.05

[[server]]
id = 10
connected_drone_ids = [8, 9]

[[client]]
id = 11
connected_drone_ids = [4]

[[client]]
id = 12
connected_drone_ids = [5]

[[client]]
id = 13
connected_drone_ids = [6]

[[client]]
id = 14
connected_drone_ids = [7]

[[server]]
id = 15
connected_drone_ids = [4, 5]