[[drone]]
id = 1
connected_node_ids = [2, 5, 8]
pdr = 0.2

[[drone]]
id = 2
connected_node_ids = [1, 3, 6]
pdr = 0.3

[[drone]]
id = 3
connected_node_ids = [2, 4, 6]
pdr = 0.25

[[drone]]
id = 4
connected_node_ids = [3, 7, 9]
pdr = 0.22

[[drone]]
id = 5
connected_node_ids = [1, 6]
pdr = 0.18

[[drone]]
id = 6
connected_node_ids = [2, 3, 5, 7, 10]
pdr = 0.27

[[drone]]
id = 7
connected_node_ids = [4, 6, 10]
pdr = 0.24

[[client]]
id = 8
connected_drone_ids = [1]

[[client]]
id = 9
connected_drone_ids = [4]

[[server]]
id = 10
connected_drone_ids = [6, 7]
