[[drone]]
id = 2
connected_node_ids = [1, 3, 4]
pdr = 0.95

[[drone]]
id = 3
connected_node_ids = [2, 5]
pdr = 0.0

[[drone]]
id = 4
connected_node_ids = [2, 5]
pdr = 0.0

[[client]]
id = 1
connected_drone_ids = [2]

[[server]]
id = 5
connected_drone_ids = [3, 4]