[[drone]]
id = 1
connected_node_ids = [2, 6, 8]
pdr = 0.9

[[drone]]
id = 2
connected_node_ids = [1, 3, 8]
pdr = 0.85

[[drone]]
id = 3
connected_node_ids = [2, 4, 7]
pdr = 0.88

[[drone]]
id = 4
connected_node_ids = [3, 5, 9]
pdr = 0.87

[[drone]]
id = 5
connected_node_ids = [4, 9, 10]
pdr = 0.9

[[client]]
id = 6
connected_drone_ids = [1]

[[client]]
id = 7
connected_drone_ids = [3]

[[client]]
id = 10
connected_drone_ids = [5]

[[server]]
id = 8
connected_drone_ids = [1, 2]

[[server]]
id = 9
connected_drone_ids = [4, 5]
