[[drone]]
id = 1
connected_node_ids = [4, 8, 11, 17, 21]  # +3/-3 + client/server
pdr = 0.934

[[drone]]
id = 2
connected_node_ids = [5, 9, 11, 17, 21]
pdr = 0.257

[[drone]]
id = 3
connected_node_ids = [6, 10, 12, 17]
pdr = 0.589

[[drone]]
id = 4
connected_node_ids = [7, 1, 13, 18]
pdr = 0.123

[[drone]]
id = 5
connected_node_ids = [8, 2, 13, 18]
pdr = 0.765

[[drone]]
id = 6
connected_node_ids = [9, 3, 14, 19]
pdr = 0.432

[[drone]]
id = 7
connected_node_ids = [10, 4, 15, 19]
pdr = 0.876

[[drone]]
id = 8
connected_node_ids = [1, 5, 15, 17]
pdr = 0.345

[[drone]]
id = 9
connected_node_ids = [2, 6, 16, 19, 20]
pdr = 0.654

[[drone]]
id = 10
connected_node_ids = [3, 7, 20, 21]
pdr = 0.012

[[client]]
id = 11
connected_drone_ids = [1, 2]

[[client]]
id = 12
connected_drone_ids = [3]

[[client]]
id = 13
connected_drone_ids = [4, 5]

[[client]]
id = 14
connected_drone_ids = [6]

[[client]]
id = 15
connected_drone_ids = [7, 8]

[[client]]
id = 16
connected_drone_ids = [9]

[[server]]
id = 17
connected_drone_ids = [1, 2, 3, 8]

[[server]]
id = 18
connected_drone_ids = [4, 5]

[[server]]
id = 19
connected_drone_ids = [6, 7, 9]

[[server]]
id = 20
connected_drone_ids = [9, 10]

[[server]]
id = 21
connected_drone_ids = [1, 2, 10]